### ISSUE TITLE
Runs for the first few steps, then crashes, 186.1

### ISSUE THREAD

**Issue by smunisto** [Gorea235/TaledensInvManagerUpdated#6]
Loaded my survival world after the 186.1 update, TIM was not running. Recompiling the script and running again produces these results and it stops again: 

Doing step 7
Processing limited item requests...
An error occured,
please give the following information to the developer:
Current step on error: 7
System.NullReferenceException: Object reference not set to an instance of an object.
   at Program.bf(String b, String c, String e, String f, Boolean g)
   at Program.bB(String b, String c, Int64 e, IMyInventory f, IMyInventory g)
   at Program.bA(Boolean b, Int32 c, String e, String f)
   at Program.bz(Boolean b)
   at Program.ProcessStepLimitedItemRequests()
   at Program.Main(String b)

**Comment by Gorea235** [comment]
I will look into this when I can, in the meantime, is it still a problem? and if so, what would be the steps to reproduce (if you're not sure, you could upload the world it happens in to the workshop, and I can try to locate the issue myself)

**Comment by Gorea235** [comment]
The problem is with something in `AddBlockRestriction` not being initialised properly I think, but without more information I don't know if I can locate the issue. I will attempt to improve the error output in the meantime.
