### ISSUE TITLE
Key Not Found Exception on run

### ISSUE THREAD

**Issue by Keyarose** [Gorea235/TaledensInvManagerUpdated#9]
When running the script with no changes it produces this error:
```
Current step on error: 8
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
at System.ThrowHelper.ThrowKeyNotFoundException()
at System.Collections.Generic.Dictionary'2.get_Item(TKey key)
at Program.bD()
at Program.ProcessStepManageRefineries()
at Program.Main(String b)
```
It had been working fine up until today, I think it may be having an issue with a block I believe is a refinery subclass from a mod that I added recently.  The Hydroponics block from [Daily Needs](https://steamcommunity.com/sharedfiles/filedetails/?id=1137868339).

**Comment by Gorea235** [comment]
The method this seems to refer is `ManageRefineries`, however it does a lot of dictionary operations, so I will attempt to debug this futher.
